routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LocaleController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Accounts\Dashboard\UserController;
use App\Http\Controllers\Accounts\Dashboard\AdminController;
use App\Http\Controllers\Reports\Dashboard\ReportController;
use App\Http\Controllers\Profile\Dashboard\ProfileController;
use App\Http\Controllers\Settings\Dashboard\SettingController;
use App\Http\Controllers\Accounts\Dashboard\CustomerController;
use App\Http\Controllers\Feedbacks\Dashboard\FeedbackController;
use App\Http\Controllers\Products\Dashboard\ProductController;

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('locale/{locale}', [LocaleController::class, 'update'])
    ->name('locale')
    ->where('locale', '(ar|en)');

Route::get('/', [DashboardController::class, 'index'])->name('home');

Route::prefix('accounts')->group(function () {
    Route::resource('customers', CustomerController::class);
    Route::resource('admins', AdminController::class);
});

Route::patch('users/{user}/activate', [UserController::class, 'activate'])->name('users.activate');

// feedback
Route::resource('feedback', FeedbackController::class)->only('index', 'show', 'destroy');

// Settings
Route::get('settings', [SettingController::class, 'index'])->name('settings.index');
Route::put('settings', [SettingController::class, 'update'])->name('settings.update');

// profile
Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
Route::put('profile/{user}', [ProfileController::class, 'update'])->name('profile.update');

//reports
Route::get('reports', [ReportController::class, 'index'])->name('reports.index');

// products
Route::resource('products', ProductController::class);
Route::get('products/{product}/images', [ProductController::class, 'showImages'])->name('products.images');
Route::put('products/{product}/images', [ProductController::class, 'updateImages'])->name('products.update.images');

routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware('dashboard.locales')->group(function () {
    Auth::routes();
});

Route::get('/', [HomeController::class, 'home']);
Route::post('/feedback', [FeedbackController::class, 'store']);
Route::get('/blog/{blog}', [BlogController::class, 'show'])->name('blog.show');

app/Http/Controllers/Accounts/Api/LoginController.php
<?php

namespace App\Http\Controllers\Accounts\Api;

use App\Models\User;
use App\Support\FirebaseToken;
use Illuminate\Auth\Events\Login;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Validation\ValidationException;
use App\Http\Requests\Accounts\Api\LoginRequest;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use App\Http\Requests\Accounts\Api\PasswordLessLoginRequest;

class LoginController extends Controller
{
    use AuthorizesRequests, ValidatesRequests;

    /**
     * @var \App\Support\FirebaseToken
     */
    private $firebaseToken;

    /**
     * LoginController constructor.
     *
     * @param \App\Support\FirebaseToken $firebaseToken
     */
    public function __construct(FirebaseToken $firebaseToken)
    {
        $this->firebaseToken = $firebaseToken;
    }

    /**
     * Handle a login request to the application.
     *
     * @param \App\Http\Requests\Accounts\Api\LoginRequest $request
     * @throws \Illuminate\Validation\ValidationException
     * @return \Illuminate\Http\Resources\Json\JsonResource
     */
    public function login(LoginRequest $request)
    {
        $user = User::where(function (Builder $query) use ($request) {
            $query->where('email', $request->username);
            $query->orWhere('phone', $request->username);
        })->first();

        if (! $user || ! Hash::check($request->password, $user->password)) {
            throw ValidationException::withMessages([
                'username' => [trans('accounts::auth.failed')],
            ]);
        }

        event(new Login('sanctum', $user, false));

        return $user->getResource()->additional([
            'token' => $user->createTokenForDevice($request->device_name),
        ]);
    }

    /**
     * Handle a login request to the application using firebase.
     *
     * @param \App\Http\Requests\Accounts\Api\PasswordLessLoginRequest $request
     * @throws \Illuminate\Auth\AuthenticationException
     * @return \Illuminate\Http\Resources\Json\JsonResource
     */
    public function firebase(PasswordLessLoginRequest $request)
    {
        $verifier = $this->firebaseToken->accessToken($request->access_token);

        $phone = $verifier->getPhoneNumber();

        $email = $verifier->getEmail();
        $name = $verifier->getName();

        $firebaseId = $verifier->getFirebaseId();

        $userQuery = User::where(compact('phone'))
            ->orWhere(compact('email'))
            ->orWhere('firebase_id', $firebaseId);

        if ($userQuery->exists()) {
            $user = $userQuery->first();
        } else {
            $user = User::forceCreate([
                'firebase_id' => $firebaseId,
                'name' => $name ?: 'Anonymous User',
                'email' => $email,
                'phone' => $phone,
            ]);
        }

        event(new Login('sanctum', $user, false));

        return $user->getResource()->additional([
            'token' => $user->createTokenForDevice($request->device_name),
        ]);
    }
}

app/Http/Controllers/Accounts/Api/ProfileController.php
<?php

namespace App\Http\Controllers\Accounts\Api;

use App\Http\Requests\Accounts\Api\CompleteProfileRequest;
use App\Models\User;
use App\Models\Doctor;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use App\Http\Requests\Accounts\Api\ProfileRequest;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class ProfileController extends Controller
{
    use AuthorizesRequests, ValidatesRequests;

    /**
     * Display the authenticated user resource.
     *
     * @return \Illuminate\Http\Resources\Json\JsonResource
     */
    public function show()
    {
        return auth()->user()->getResource();
    }

    public function search(Request $request)
    {
        $users = User::filter()->paginate();

        return Response()->json([
            'data' => $users,
        ]);
    }

    /**
     * Update the authenticated user profile.
     *
     * @param \App\Http\Requests\Accounts\Api\ProfileRequest $request
     * @return \Illuminate\Http\Resources\Json\JsonResource
     */
    public function update(ProfileRequest $request)
    {
        $user = auth()->user();

        $user->update($request->allWithHashedPassword());

        $user->addAllMediaFromTokens();

        return $user->getResource();
    }

    /**
     * Update the authenticated user profile.
     *
     * @param \App\Http\Requests\Accounts\Api\ProfileRequest $request
     * @return \Illuminate\Http\Resources\Json\JsonResource
     */
    public function complete(CompleteProfileRequest $request)
    {
        $user = auth()->user();

        $user->update($request->allWithHashedPassword());

        $user->addAllMediaFromTokens();

        return $user->getResource();
    }
}

app/Http/Controllers/Accounts/Api/RegisterController.php
<?php

namespace App\Http\Controllers\Accounts\Api;

use App\Models\Customer;
use App\Models\User;
use Illuminate\Routing\Controller;
use Illuminate\Auth\Events\Registered;
use App\Http\Requests\Accounts\Api\RegisterRequest;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class RegisterController extends Controller
{
    use AuthorizesRequests, ValidatesRequests;

    /**
     * Handle a login request to the application.
     *
     * @param \App\Http\Requests\Accounts\Api\RegisterRequest $request
     * @return \Illuminate\Http\Resources\Json\JsonResource
     */
    public function register(RegisterRequest $request)
    {
        $user = Customer::create($request->allWithHashedPassword());

        $user->addAllMediaFromTokens();

        event(new Registered($user));

        return $user->getResource()->additional([
            'token' => $user->createTokenForDevice($request->device_name),
        ]);
    }
}

app/Http/Controllers/Accounts/Api/ResetPasswordController.php
<?php

namespace App\Http\Controllers\Accounts\Api;

use App\Models\User;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use App\Models\ResetPasswordCode;
use Illuminate\Auth\Events\Login;
use App\Models\ResetPasswordToken;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Validation\ValidationException;
use Illuminate\Foundation\Validation\ValidatesRequests;
use App\Http\Requests\Accounts\Api\ResetPasswordRequest;
use App\Http\Requests\Accounts\Api\ForgetPasswordRequest;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use App\Notifications\Accounts\PasswordUpdatedNotification;
use App\Http\Requests\Accounts\Api\ResetPasswordCodeRequest;
use App\Notifications\Accounts\SendForgetPasswordCodeNotification;

class ResetPasswordController extends Controller
{
    use AuthorizesRequests, ValidatesRequests;

    /**
     * Send the forget password code to the user.
     *
     * @param \App\Http\Requests\Accounts\Api\ForgetPasswordRequest $request
     * @throws \Illuminate\Validation\ValidationException
     * @return \Illuminate\Http\JsonResponse
     */
    public function forget(ForgetPasswordRequest $request)
    {
        $user = User::where(function (Builder $query) use ($request) {
            $query->where('email', $request->username);
            $query->orWhere('phone', $request->username);
        })->first();

        if (! $user) {
            throw ValidationException::withMessages([
                'username' => [trans('accounts::auth.failed')],
            ]);
        }

        $resetPasswordCode = ResetPasswordCode::updateOrCreate([
            'username' => $request->username,
        ], [
            'username' => $request->username,
            'code' => Str::random(6),
        ]);

        if (env('APP_ENV') == 'local') {

            Storage::disk('public')->append(
                'verification.txt',
                "Your verification code  is {$resetPasswordCode->code} generated at " . now()->toDateTimeString(),
                "\n"
            );
        }
        $user->notify(new SendForgetPasswordCodeNotification($resetPasswordCode->code));

        return response()->json([
            'message' => trans('accounts::auth.messages.forget-password-code-sent'),
            'links' => [
                'code' => [
                    'href' => route('api.password.code'),
                    'method' => 'POST',
                ],
            ],
        ]);
    }

    /**
     * Get the reset password token using verification code.
     *
     * @param \App\Http\Requests\Accounts\Api\ResetPasswordCodeRequest $request
     * @throws \Illuminate\Validation\ValidationException
     * @return \Illuminate\Http\JsonResponse
     */
    public function code(ResetPasswordCodeRequest $request)
    {
        $resetPasswordCode = ResetPasswordCode::where('username', $request->username)
            ->where('code', $request->code)
            ->first();

        $user = User::where(function (Builder $query) use ($request) {
            $query->where('email', $request->username);
            $query->orWhere('phone', $request->username);
        })->first();

        if (! $resetPasswordCode || $resetPasswordCode->isExpired() || ! $user) {
            throw ValidationException::withMessages([
                'code' => [
                    trans('validation.exists', [
                        'attribute' => trans('accounts::auth.attributes.code'),
                    ]),
                ],
            ]);
        }

        $resetPasswordCode->delete();

        ResetPasswordToken::forceCreate([
            'user_id' => $user->id,
            'token' => $token = Str::random(80),
        ]);


        if (env('APP_ENV') == 'local') {

            Storage::disk('public')->append(
                'verification.txt',
                "Your verification reset_token  is {$token} generated at " . now()->toDateTimeString(),
                "\n"
            );
        }

        return response()->json([
            'reset_token' => $token,
            'links' => [
                'reset' => [
                    'href' => route('api.password.reset'),
                    'method' => 'POST',
                ],
            ],
        ]);
    }

    public function reset(ResetPasswordRequest $request)
    {
        $resetPasswordToken = ResetPasswordToken::where($request->only('token'))->first();

        if (! $resetPasswordToken || $resetPasswordToken->isExpired()) {
            throw ValidationException::withMessages([
                'token' => [
                    trans('validation.exists', [
                        'attribute' => trans('accounts::auth.attributes.token'),
                    ]),
                ],
            ]);
        }

        $user = $resetPasswordToken->user;

        $user->update([
            'password' => Hash::make($request->password),
        ]);

        $user->notify(new PasswordUpdatedNotification());

        event(new Login('sanctum', $user, false));

        $resetPasswordToken->delete();

        return $user->getResource()->additional([
            'token' => $user->createTokenForDevice($request->device_name),
        ]);
    }
}

app/Http/Controllers/Accounts/SelectController.php
<?php

namespace App\Http\Controllers\Accounts;

use App\Models\Page;
use App\Models\User;
use App\Models\Customer;
use Illuminate\Routing\Controller;
use App\Http\Resources\SelectResource;
use App\Http\Resources\PageSelectResource;
use App\Http\Filters\Accounts\SelectFilter;

class SelectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param \App\Http\Filters\Accounts\SelectFilter $filter
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index(SelectFilter $filter)
    {
        $users = User::filter($filter)->paginate();

        return SelectResource::collection($users);
    }

    /**
     * Display a listing of the resource.
     *
     * @param \App\Http\Filters\Accounts\SelectFilter $filter
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function customers(SelectFilter $filter)
    {
        $users = Customer::filter($filter)->paginate();

        return SelectResource::collection($users);
    }

    /**
     * Display a listing of the resource.
     *
     * @param SelectFilter $filter
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function pages(SelectFilter $filter)
    {
        $pages = Page::filter($filter)->paginate();

        return PageSelectResource::collection($pages);
    }
}

app/View/Components/Layout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Layout extends Component
{
    /**
     * @var string
     */
    public $title;

    /**
     * @var array
     */
    public $breadcrumbs = [];

    /**
     * Create a new component instance.
     *
     * @param null $title
     * @param array $breadcrumbs
     */
    public function __construct($title = null, $breadcrumbs = [])
    {
        $this->title = $title;
        $this->breadcrumbs = $breadcrumbs;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('dashboard::master');
    }
}

resources/views/dashboard/accounts/admins/create.blade.php
<x-layout :title="trans('admins.actions.create')" :breadcrumbs="['dashboard.admins.create']">
    {{ BsForm::resource('admins')->post(route('dashboard.admins.store')) }}
    @component('dashboard::components.box')
        @slot('title', trans('admins.actions.create'))

        @include('dashboard.accounts.admins.partials.form')

        @slot('footer')
            {{ BsForm::submit()->label(trans('admins.actions.save')) }}
        @endslot
    @endcomponent
    {{ BsForm::close() }}
</x-layout>

resources/views/dashboard/accounts/admins/edit.blade.php
<x-layout :title="$admin->name" :breadcrumbs="['dashboard.admins.edit', $admin]">
    {{ BsForm::resource('admins')->putModel($admin, route('dashboard.admins.update', $admin), ['files' => true]) }}
    @component('dashboard::components.box')
        @slot('title', trans('admins.actions.edit'))

        @include('dashboard.accounts.admins.partials.form')

        @slot('footer')
            {{ BsForm::submit()->label(trans('admins.actions.save')) }}
        @endslot
    @endcomponent
    {{ BsForm::close() }}
</x-layout>

resources/views/dashboard/accounts/admins/index.blade.php
<x-layout :title="trans('admins.plural')" :breadcrumbs="['dashboard.admins.index']">
    @include('dashboard.accounts.admins.partials.filter')
    @component('dashboard::components.table-box')

        @slot('title', trans('admins.actions.list'))

        @slot('tools')
            @include('dashboard.accounts.admins.partials.actions.create')
        @endslot

        <thead>
        <tr>
            <th>@lang('admins.attributes.name')</th>
            <th class="d-none d-md-table-cell">@lang('admins.attributes.email')</th>
            <th>@lang('admins.attributes.phone')</th>
            <th>@lang('admins.attributes.created_at')</th>
            <th style="width: 160px">...</th>
        </tr>
        </thead>
        <tbody>
        @forelse($admins as $admin)
            <tr>
                <td>
                    <a href="{{ route('dashboard.admins.show', $admin) }}"
                       class="text-decoration-none text-ellipsis">
                            <span class="index-flag">
                            @include('dashboard.accounts.admins.partials.flags.svg')
                            </span>
                        <img src="{{ $admin->getAvatar() }}"
                             alt="Product 1"
                             class="img-circle img-size-32 mr-2">
                        {{ $admin->name }}
                    </a>
                </td>

                <td class="d-none d-md-table-cell">
                    {{ $admin->email }}
                </td>
                <td>{{ $admin->phone }}</td>
                <td>{{ $admin->created_at->format('Y-m-d') }}</td>

                <td style="width: 160px">
                    @include('dashboard.accounts.admins.partials.actions.show')
                    @include('dashboard.accounts.admins.partials.actions.edit')
                    @include('dashboard.accounts.admins.partials.actions.delete')
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="100" class="text-center">@lang('admins.empty')</td>
            </tr>
        @endforelse

        @if($admins->hasPages())
            @slot('footer')
                {{ $admins->links() }}
            @endslot
        @endif
    @endcomponent
</x-layout>

resources/views/dashboard/accounts/admins/show.blade.php
<x-layout :title="$admin->name" :breadcrumbs="['dashboard.admins.show', $admin]">
    @component('dashboard::components.box')
        @slot('bodyClass', 'p-0')

        <table class="table table-striped table-middle">
            <tbody>
            <tr>
                <th width="200">@lang('admins.attributes.name')</th>
                <td>{{ $admin->name }}</td>
            </tr>
            <tr>
                <th width="200">@lang('admins.attributes.email')</th>
                <td>{{ $admin->email }}</td>
            </tr>
            <tr>
                <th width="200">@lang('admins.attributes.phone')</th>
                <td>{{ $admin->phone }}</td>
            </tr>
            <tr>
                <th width="200">@lang('admins.attributes.avatar')</th>
                <td>
                    <img src="{{ $admin->getAvatar() }}"
                         class="img img-size-64"
                         alt="{{ $admin->name }}">
                </td>
            </tr>
            </tbody>
        </table>

        @slot('footer')
            @include('dashboard.accounts.admins.partials.actions.edit')
            @include('dashboard.accounts.admins.partials.actions.delete')
        @endslot
    @endcomponent
</x-layout>